version: '3'
services:
  mongo:
    build: ./config/mongo
    image: docker_mongo
    container_name: mongo
    env_file:
      - .env
    volumes:
      - ./config/mongo:/mnt/mongo
      - mongodbdata:/var/lib/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
  webui:
    image: docker_open5gs
    restart: on-failure
    container_name: webui
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=webui
    volumes:
      - ./webui:/mnt/webui
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000/tcp"
    ports:
      - "3000:3000/tcp"
    networks:
      default:
        ipv4_address: ${WEBUI_IP}
  nrf:
    image: docker_open5gs
    restart: on-failure
    container_name: nrf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nrf-1
    volumes:
      - ./config/open5gs/nrf:/mnt/nrf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${NRF_IP}
  ausf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
    container_name: ausf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ausf-1
    volumes:
      - ./config/open5gs/ausf:/mnt/ausf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${AUSF_IP}
  udr:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
      - mongo
    container_name: udr
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udr-1
    volumes:
      - ./config/open5gs/udr:/mnt/udr
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${UDR_IP}
  udm:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
    container_name: udm
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udm-1
    volumes:
      - ./config/open5gs/udm:/mnt/udm
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${UDM_IP}
  pcf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
      - mongo
    container_name: pcf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcf-1
    volumes:
      - ./config/open5gs/pcf:/mnt/pcf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${PCF_IP}
  bsf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
      - mongo
    container_name: bsf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=bsf-1
    volumes:
      - ./config/open5gs/bsf:/mnt/bsf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${BSF_IP}
  nssf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
      - mongo
    container_name: nssf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nssf-1
    volumes:
      - ./config/open5gs/nssf:/mnt/nssf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${NSSF_IP}
  smf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
    container_name: smf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smf-1
    volumes:
      - ./config/open5gs/smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${SMF_IP}
  upf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - nrf
      - smf
    container_name: upf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=upf-1
    volumes:
      - ./config/open5gs/upf:/mnt/upf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
    # ports:
    #   - "2152:2152/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      #- net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        ipv4_address: ${UPF_IP}
  amf:
    image: docker_open5gs
    restart: on-failure
    depends_on:
      - smf
      - upf
      - nrf
      - ausf
      - udm
      - udr
      - pcf
      - bsf
    container_name: amf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=amf-1
    volumes:
      - ./config/open5gs/amf:/mnt/amf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "38412/sctp"
      - "7777/tcp"
    # ports:
    #   - "38412:38412/sctp"
    networks:
      default:
        ipv4_address: ${AMF_IP}
  pcrf:
    image: docker_open5gs
    restart: on-failure
    container_name: pcrf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcrf-1
    depends_on:
      - mongo
    volumes:
      - ./config/open5gs/pcrf:/mnt/pcrf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
    networks:
      default:
        ipv4_address: ${PCRF_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
volumes:
  mongodbdata: {}
  dbdata: {}
