db_uri: mongodb://MONGO_IP/open5gs

logger:
    file: /open5gs/install/var/log/open5gs/pcf.log

parameter:

pcf:
    sbi:
      - addr: PCF_IP
        port: 7777

nrf:
    sbi:
      - addr:
          - NRF_IP
        port: 7777
